In [ ]:
import tensorflow as tf

In [ ]:
# indices -> contains the positions of each value.
# values -> contains each individual value to be mapped inside the sparse tensor.
# dense_shape -> contains the actual size of the tensor as a whole.
A = tf.sparse.SparseTensor(
    indices=[[1,1], [3,4]], values=[11,56], dense_shape=[5,6]
)
A

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(A)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
# No, this doesn't work. You need to manually specify the batch as well.
# B = tf.sparse.SparseTensor(
#     indices=[[[1,1]], [[0,0]]], values=[-1,-2], dense_shape=[2,5,6]
# )

# [[batch, row, col], ...]
B = tf.sparse.SparseTensor(
    indices=[[0,1,1], [1,0,0], [1,3,0]], values=[-1,-2,-3], dense_shape=[2,5,6]
)

B

SparseTensor(indices=tf.Tensor(
[[0 1 1]
 [1 0 0]
 [1 3 0]], shape=(3, 3), dtype=int64), values=tf.Tensor([-1 -2 -3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([2 5 6], shape=(3,), dtype=int64))

In [ ]:
tf.sparse.to_dense(B)

<tf.Tensor: shape=(2, 5, 6), dtype=int32, numpy=
array([[[ 0,  0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[-2,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [-3,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]]], dtype=int32)>