In [ ]:
import tensorflow as tf

In [ ]:
# to add some previsibility
tf.random.set_seed(10)

t1 = tf.random.uniform((3,4), minval=10, maxval=99, dtype=tf.int32, seed=5)
t2 = tf.random.uniform((5,3), minval=10, maxval=99, dtype=tf.int32, seed=5)

print(t1)
print(t2)

tf.Tensor(
[[64 35 37 58]
 [13 24 54 58]
 [46 14 70 97]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[73 39 34]
 [48 92 53]
 [98 95 66]
 [23 11 30]
 [37 28 83]], shape=(5, 3), dtype=int32)


In [ ]:
# error: incompatible shapes
# tf.math.add(t1, t2)

# broadcasting: expansion of the dimensions of matrices to make them compatible.
tf.math.add(t1, [2])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[66, 37, 39, 60],
       [15, 26, 56, 60],
       [48, 16, 72, 99]], dtype=int32)>

In [ ]:
# ELEMENT WISE
tf.math.multiply(t2, [2])
tf.math.pow(t2, [2])
tf.math.sqrt(tf.cast(t2, dtype=tf.float32), [2])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[8.5440035, 6.244998 , 5.8309517],
       [6.928203 , 9.591663 , 7.28011  ],
       [9.899495 , 9.746795 , 8.124039 ],
       [4.7958317, 3.3166249, 5.477226 ],
       [6.0827627, 5.2915025, 9.110434 ]], dtype=float32)>

In [ ]:
temp = tf.random.normal((3,3), mean=0, stddev=0.5, dtype=tf.float32)
print(temp)
print(tf.math.abs(temp))

tf.Tensor(
[[-0.69071305 -0.14288633 -0.04043218]
 [-0.6096775  -0.06390882  1.3119876 ]
 [-0.20100644 -0.76196223  0.32208973]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.69071305 0.14288633 0.04043218]
 [0.6096775  0.06390882 1.3119876 ]
 [0.20100644 0.76196223 0.32208973]], shape=(3, 3), dtype=float32)


In [ ]:
temp = tf.random.uniform((3,3), minval=1, maxval=9)

temp, tf.math.sigmoid(temp)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[4.337265 , 5.642888 , 5.391636 ],
        [8.833223 , 2.4595566, 2.792776 ],
        [8.585617 , 8.234849 , 1.1245737]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.9870964 , 0.99646986, 0.9954661 ],
        [0.9998542 , 0.9212575 , 0.9422842 ],
        [0.99981326, 0.9997348 , 0.7548361 ]], dtype=float32)>)