In [ ]:
import tensorflow as tf

In [ ]:
tf.random.set_seed(10)

t1 = tf.random.uniform((3,3), minval=10, maxval=99, dtype=tf.float32, seed=5)
t2 = tf.random.uniform((3,3), minval=10, maxval=99, dtype=tf.float32, seed=5)

t1, t2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[98.060295, 42.801506, 20.338509],
        [86.77901 , 52.351753, 50.67973 ],
        [59.203354, 41.111343, 97.92624 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[63.196625, 20.382484, 94.481964],
        [27.182152, 17.855484, 51.201702],
        [41.111584, 95.10234 , 58.049408]], dtype=float32)>)

In [ ]:
# cross product
tf.linalg.cross(t1, t2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 3629.4211  , -7979.6045  ,  -706.19824 ],
       [ 1775.5876  , -3065.649   ,   126.447876],
       [-6926.5254  ,   589.1831  ,  3940.225   ]], dtype=float32)>

In [ ]:
# puts each row in a diagonal matrix
tf.linalg.diag(t2)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[63.196625,  0.      ,  0.      ],
        [ 0.      , 20.382484,  0.      ],
        [ 0.      ,  0.      , 94.481964]],

       [[27.182152,  0.      ,  0.      ],
        [ 0.      , 17.855484,  0.      ],
        [ 0.      ,  0.      , 51.201702]],

       [[41.111584,  0.      ,  0.      ],
        [ 0.      , 95.10234 ,  0.      ],
        [ 0.      ,  0.      , 58.049408]]], dtype=float32)>

In [ ]:
tf.linalg.det(t1), tf.linalg.det(t2)

(<tf.Tensor: shape=(), dtype=float32, numpy=72627.09>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-56595.438>)

In [ ]:
tf.linalg.adjoint(t1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[98.060295, 86.77901 , 59.203354],
       [42.801506, 52.351753, 41.111343],
       [20.338509, 50.67973 , 97.92624 ]], dtype=float32)>

In [ ]:
# Inverse matrix
tf.linalg.inv(t1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.04190034, -0.04619831,  0.01520662],
       [-0.07569537,  0.11563967, -0.04412562],
       [ 0.00644666, -0.02061763,  0.01954308]], dtype=float32)>

In [ ]:
# Singular Value Decomposition
s, u, v = tf.linalg.svd(t1)

s, u, v

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([188.78337 ,  61.708015,   6.234377], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.53581476, -0.6519194 , -0.53656673],
        [ 0.5974837 , -0.15626654,  0.78650755],
        [ 0.5965869 ,  0.7420122 , -0.30578122]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.7400606 , -0.5438264 , -0.39568058],
        [ 0.41708907, -0.09040706,  0.90435797],
        [ 0.527586  ,  0.83431375, -0.15991734]], dtype=float32)>)

In [ ]:
# different ways of doing the same thing
x1 = tf.linalg.matmul(t1, t2, transpose_a=True, transpose_b=True)
x2 = tf.linalg.matrix_transpose(t1)@tf.linalg.matrix_transpose(t2)

x1, x2, x1 == x2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[13559.501 ,  7246.283 , 15721.0205],
        [ 7656.25  ,  4203.174 ,  9124.901 ],
        [11570.567 ,  6471.7456, 11340.47  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[13559.501 ,  7246.283 , 15721.0205],
        [ 7656.25  ,  4203.174 ,  9124.901 ],
        [11570.567 ,  6471.7456, 11340.47  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)