In [68]:
import tensorflow as tf
import numpy as np
# expand_dims, reshape, squeeze, concat

In [2]:
A = tf.constant([
    [[[2, 9], [3,  6], [1, 3], [3, 0]],
     [[0, 3], [8, -2], [5, 0], [2, 0]],
     [[0, 5], [2,  1], [1, 3], [5, 0]],
     [[0, 9], [8,  2], [1, 3], [2, 5]]]
])

B = tf.constant([
    [[[  2], [ -3], [ 2], [ 5]],
     [[  3], [  9], [ 9], [ 6]],
     [[ 12], [  2], [ 3], [ 1]],
     [[  6], [ 1 ], [ 0], [ 1]]]
])

A.shape, B.shape

(TensorShape([1, 4, 4, 2]), TensorShape([1, 4, 4, 1]))

In [4]:
# reshape
tf.reshape(A, (1, 4, 8)), tf.reshape(B, (1, 4, 4))

(<tf.Tensor: shape=(1, 4, 8), dtype=int32, numpy=
 array([[[ 2,  9,  3,  6,  1,  3,  3,  0],
         [ 0,  3,  8, -2,  5,  0,  2,  0],
         [ 0,  5,  2,  1,  1,  3,  5,  0],
         [ 0,  9,  8,  2,  1,  3,  2,  5]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
 array([[[ 2, -3,  2,  5],
         [ 3,  9,  9,  6],
         [12,  2,  3,  1],
         [ 6,  1,  0,  1]]], dtype=int32)>)

In [29]:
# tf.einsum("bij -> bji", tf.reshape(B, (1,4,4)))
tf.einsum("...ij -> ...ji", tf.reshape(B, (1,4,4)))

<tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
array([[[ 2,  3, 12,  6],
        [-3,  9,  2,  1],
        [ 2,  9,  3,  0],
        [ 5,  6,  1,  1]]], dtype=int32)>

In [38]:
# expand_dims -> adds 1 dimension before the specified axis
print(A.shape)
print(tf.expand_dims(A, axis=0).shape)
print(tf.expand_dims(A, axis=1).shape)
print(tf.expand_dims(A, axis=2).shape)
print(tf.expand_dims(A, axis=3).shape)
print(tf.expand_dims(A, axis=4).shape)

(1, 4, 4, 2)
(1, 1, 4, 4, 2)
(1, 1, 4, 4, 2)
(1, 4, 1, 4, 2)
(1, 4, 4, 1, 2)
(1, 4, 4, 2, 1)


In [48]:
# squeeze -> removes dimensions with size = 1
print(A.shape)
print(tf.squeeze(A).shape)
print(tf.squeeze(A, axis=0).shape)
# print(tf.squeeze(A, axis=1).shape) # error: axis 1 has dimension = 4

(1, 4, 4, 2)
(4, 4, 2)
(4, 4, 2)


In [75]:
# reshape
print(A.shape)

# you may use -1 to make tensorflow automatically calculate the remaining size for the dimensions.
print(tf.reshape(A, (1, 4, -1)).shape)

# creates a one dimensional tensor
print(tf.reshape(A, np.prod(A.shape)).shape)
print(tf.reshape(A, -1).shape) # same result

(1, 4, 4, 2)
(1, 4, 8)
(32,)
(32,)
