In [1]:
import tensorflow as tf

In [8]:
A = tf.constant([[7, 8, 9], [10, 5, 0]])
B = tf.constant([[3, -1, 0], [4, 5, 6]])

A, B

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10,  5,  0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 3, -1,  0],
        [ 4,  5,  6]], dtype=int32)>)

In [9]:
# concat concatenates a tensor along the specified axis.
tf.concat([A, B], axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10,  5,  0],
       [ 3, -1,  0],
       [ 4,  5,  6]], dtype=int32)>

In [10]:
tf.concat([A, B], axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 7,  8,  9,  3, -1,  0],
       [10,  5,  0,  4,  5,  6]], dtype=int32)>

In [12]:
# stack creates a new dimension in the specified axis.
tf.stack([A, B], axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 7,  8,  9],
        [10,  5,  0]],

       [[ 3, -1,  0],
        [ 4,  5,  6]]], dtype=int32)>

In [13]:
tf.stack([A, B], axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 7,  8,  9],
        [ 3, -1,  0]],

       [[10,  5,  0],
        [ 4,  5,  6]]], dtype=int32)>

In [16]:
tf.random.set_seed(10)

C = tf.random.uniform((4, 3), minval=-1, maxval=10, dtype=tf.int32, seed=5)
D = tf.random.uniform((4, 3), minval=-1, maxval=10, dtype=tf.int32, seed=5)

C, D

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[2, 0, 9],
        [5, 6, 1],
        [1, 3, 8],
        [4, 2, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[4, 6, 9],
        [9, 6, 8],
        [9, 5, 5],
        [9, 8, 7]], dtype=int32)>)

In [20]:
print(tf.concat([C, D], axis=0))
print(tf.concat([C, D], axis=1))

tf.Tensor(
[[2 0 9]
 [5 6 1]
 [1 3 8]
 [4 2 6]
 [4 6 9]
 [9 6 8]
 [9 5 5]
 [9 8 7]], shape=(8, 3), dtype=int32)
tf.Tensor(
[[2 0 9 4 6 9]
 [5 6 1 9 6 8]
 [1 3 8 9 5 5]
 [4 2 6 9 8 7]], shape=(4, 6), dtype=int32)


In [21]:
tf.stack([C, D], axis=0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[2, 0, 9],
        [5, 6, 1],
        [1, 3, 8],
        [4, 2, 6]],

       [[4, 6, 9],
        [9, 6, 8],
        [9, 5, 5],
        [9, 8, 7]]], dtype=int32)>

In [22]:
tf.stack([C, D], axis=1)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[2, 0, 9],
        [4, 6, 9]],

       [[5, 6, 1],
        [9, 6, 8]],

       [[1, 3, 8],
        [9, 5, 5]],

       [[4, 2, 6],
        [9, 8, 7]]], dtype=int32)>

In [25]:
#
tf.stack([C, D], axis=2)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[2, 4],
        [0, 6],
        [9, 9]],

       [[5, 9],
        [6, 6],
        [1, 8]],

       [[1, 9],
        [3, 5],
        [8, 5]],

       [[4, 9],
        [2, 8],
        [6, 7]]], dtype=int32)>

In [30]:
# same output
print(tf.stack([C, D], axis=0))
# 4,3 and 4,3 -> 1,4,3 and 1,4,3 -> 2,4,3
print(tf.concat([tf.expand_dims(t, axis=0) for t in [C, D]], axis=0))

tf.Tensor(
[[[2 0 9]
  [5 6 1]
  [1 3 8]
  [4 2 6]]

 [[4 6 9]
  [9 6 8]
  [9 5 5]
  [9 8 7]]], shape=(2, 4, 3), dtype=int32)
tf.Tensor(
[[[2 0 9]
  [5 6 1]
  [1 3 8]
  [4 2 6]]

 [[4 6 9]
  [9 6 8]
  [9 5 5]
  [9 8 7]]], shape=(2, 4, 3), dtype=int32)
