In [2]:
import tensorflow as tf

In [20]:
A = tf.constant([
    "Franz", "Bonaparta", "Emil", "Sebe"
])
B = tf.constant([
    ["Franz", "Bonaparta"],
    ["Emil", "Sebe"],
    ["Helmuth", "Voss"]
])

A, B

(<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'Franz', b'Bonaparta', b'Emil', b'Sebe'], dtype=object)>,
 <tf.Tensor: shape=(3, 2), dtype=string, numpy=
 array([[b'Franz', b'Bonaparta'],
        [b'Emil', b'Sebe'],
        [b'Helmuth', b'Voss']], dtype=object)>)

In [22]:
tf.strings.join(A, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'Franz+Bonaparta+Emil+Sebe'>

In [23]:
# This joins values of rows, not columns
tf.strings.join(B, separator=" ")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Franz Emil Helmuth', b'Bonaparta Sebe Voss'], dtype=object)>

In [26]:
tf.strings.length(A, unit="BYTE")
tf.strings.length(A, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 9, 4, 4], dtype=int32)>

In [29]:
tf.strings.length(B, unit="UTF8_CHAR")

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 9],
       [4, 4],
       [7, 4]], dtype=int32)>

In [31]:
tf.strings.lower(B)

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'franz', b'bonaparta'],
       [b'emil', b'sebe'],
       [b'helmuth', b'voss']], dtype=object)>