In [1]:
import tensorflow as tf

In [12]:
x = tf.constant([1, 2, 3])
x_var = tf.Variable(x, name="var1")

x_var.assign_add([-1, -2, -3])
x_var.assign_sub([1, 0, 9])

print(x_var)
print(x_var.assign([1,3,4]))

<tf.Variable 'var1:0' shape=(3,) dtype=int32, numpy=array([-1,  0, -9], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([1, 3, 4], dtype=int32)>


In [13]:
with tf.device("GPU:0"):
  A = tf.constant([3, 1, 1])

x_var.device, A.device

('/job:localhost/replica:0/task:0/device:CPU:0',
 '/job:localhost/replica:0/task:0/device:GPU:0')

In [17]:
# WARNING: When switching between CPU and GPU, TensorFlow must transfer data between the two, which can introduce significant overhead. This is just a didatic example.
# >>
# If you move B to the CPU and then perform the multiplication on the GPU, TensorFlow will need to copy B from the CPU to the GPU, which can reduce the performance benefit.

with tf.device("CPU:0"):
  B = tf.constant([[1,2,3],[4,5,6]])

with tf.device("GPU:0"):
  # broadcasting
  C = B * [-1]

print(B, B.device)
print(C, C.device)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[-1 -2 -3]
 [-4 -5 -6]], shape=(2, 3), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0
