In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
t = tf.constant([
    [3, 4, 5],
    [-9, 12, 43],
    [0, 30, 2],
])

print(t)

tf.Tensor(
[[ 3  4  5]
 [-9 12 43]
 [ 0 30  2]], shape=(3, 3), dtype=int32)


In [ ]:
t2 = tf.constant([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

mat_mul = tf.matmul(t, t2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, grad_a=False, grad_b=False, name=None)

# also matrix multiplication, but with less options
# mat_mul = t@t2

print(mat_mul)

tf.Tensor(
[[ 66  78  90]
 [386 432 478]
 [166 198 230]], shape=(3, 3), dtype=int32)


In [ ]:
# 4x3
t3 = tf.constant([[2, 3, 4], [5, 6, 7], [8, 9, 10], [9, 9, 9]])

# error: t is (3x3) and t3 is (4x3)
# mat_mul = tf.matmul(t, t3, transpose_a=False, transpose_b=False)

# ok after tranposition
mat_mul = tf.matmul(t, t3, transpose_b=True)

print(mat_mul)

tf.Tensor(
[[ 38  74 110 108]
 [190 328 466 414]
 [ 98 194 290 288]], shape=(3, 4), dtype=int32)


In [ ]:
tf.fill(
    (3, 4), value=9.9
)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[9.9, 9.9, 9.9, 9.9],
       [9.9, 9.9, 9.9, 9.9],
       [9.9, 9.9, 9.9, 9.9]], dtype=float32)>

In [ ]:
# creates the the identity matrix
print(
    tf.eye(num_rows=5, num_columns=5)
)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [ ]:
%%time
# <- measures time execution of this cell

temp = tf.ones((3,5), dtype=tf.float32)
# casting
tf.cast(temp, dtype=tf.int32)

CPU times: user 4.96 ms, sys: 0 ns, total: 4.96 ms
Wall time: 4.77 ms


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [ ]:
# uniform distribution: every value in a certain range has the same chance of being picked at random.
tf.random.uniform((5,5), minval=5, maxval=15)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 5.152713 , 13.303335 ,  7.491578 ,  6.3808036, 12.982522 ],
       [11.684562 , 14.4960785, 14.820551 ,  8.01841  ,  5.0652766],
       [10.694742 , 14.505318 , 14.059206 , 14.946688 ,  6.3239775],
       [ 9.979809 ,  8.898498 ,  6.844445 , 14.416056 ,  7.4169087],
       [11.023979 , 10.935231 , 11.281992 ,  9.913799 , 12.161488 ]],
      dtype=float32)>

In [ ]:
# normal/gaussian distribution: values closer to the mean have more chance of being picked.
# Also, the standard deviation widens or shortens the range of values which are possible to be picked.
tf.random.normal((5,5), mean=0, stddev=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.15956414,  1.4019725 , -0.28559023,  0.3916463 ,  0.74415344],
       [ 0.89223784,  1.0937997 , -0.7862414 , -0.59452885, -0.44168225],
       [ 0.74528027,  1.3139004 ,  0.19513634,  0.9183597 , -0.61616707],
       [ 0.8219879 ,  0.02944656, -0.8173862 ,  1.6200213 , -0.9257649 ],
       [ 0.57642627, -0.5127325 , -0.63143694, -0.05808721,  1.1311239 ]],
      dtype=float32)>