In [ ]:
import tensorflow as tf

In [ ]:
A = tf.random.uniform((4,3), minval=-1, maxval=10, dtype=tf.int32)
B = tf.random.uniform((4,3), minval=-1, maxval=10, dtype=tf.int32)

A, B

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[9, 1, 7],
        [3, 7, 7],
        [1, 4, 8],
        [2, 8, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[2, 2, 9],
        [0, 0, 4],
        [1, 9, 1],
        [1, 5, 9]], dtype=int32)>)

In [12]:
# [1,1] -> 1 padding at top,  1 padding at bottom
# [2,2] -> 2 padding at left, 2 padding at right
pad = [[1,1], [2, 2]]
# tf.pad(A, paddings=pad, mode="CONSTANT", constant_values=0)
tf.pad(A, paddings=pad, mode="CONSTANT", constant_values=-1)

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[-1, -1, -1, -1, -1, -1, -1],
       [-1, -1,  9,  1,  7, -1, -1],
       [-1, -1,  3,  7,  7, -1, -1],
       [-1, -1,  1,  4,  8, -1, -1],
       [-1, -1,  2,  8,  6, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]], dtype=int32)>

In [ ]:
tf.pad(A, paddings=pad, mode="REFLECT")

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[7, 7, 3, 7, 7, 7, 3],
       [7, 1, 9, 1, 7, 1, 9],
       [7, 7, 3, 7, 7, 7, 3],
       [8, 4, 1, 4, 8, 4, 1],
       [6, 8, 2, 8, 6, 8, 2],
       [8, 4, 1, 4, 8, 4, 1]], dtype=int32)>

In [ ]:
tf.pad(A, paddings=pad, mode="SYMMETRIC")

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[1, 9, 9, 1, 7, 7, 1],
       [1, 9, 9, 1, 7, 7, 1],
       [7, 3, 3, 7, 7, 7, 7],
       [4, 1, 1, 4, 8, 8, 4],
       [8, 2, 2, 8, 6, 6, 8],
       [8, 2, 2, 8, 6, 6, 8]], dtype=int32)>